# Generated by Django 5.2.7 on 2025-10-06 17:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text')),
                ('mission', wagtail.fields.RichTextField(blank=True, help_text='Mission statement')),
                ('vision', wagtail.fields.RichTextField(blank=True, help_text='Vision statement')),
                ('body', wagtail.fields.StreamField([('about', 3), ('team', 11), ('testimonials', 15), ('rich_text', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section title', 'max_length': 255}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'About content'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional image', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 150}), 6: ('wagtail.blocks.TextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.EmailBlock', (), {'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('name', 4), ('role', 5), ('bio', 6), ('photo', 7), ('email', 8), ('phone', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': 'Testimonial text'}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('quote', 12), ('author', 4), ('role', 13), ('avatar', 7)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('events', 8), ('rich_text', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.DateBlock', (), {'required': False}), 2: ('wagtail.blocks.TimeBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'Event registration URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('date', 1), ('time', 2), ('location', 3), ('description', 4), ('image', 5), ('registration_link', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'verbose_name': 'Events Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FlexiblePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 6), ('about', 10), ('events', 19), ('gallery', 22), ('testimonials', 27), ('team', 33), ('rules', 37), ('rich_text', 35), ('html', 38)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subheading text', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Hero description', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Call to action button text', 'max_length': 100, 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'Call to action button link', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('description', 2), ('background_image', 3), ('cta_text', 4), ('cta_link', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section title', 'max_length': 255}), 8: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'About content'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional image', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('content', 8), ('image', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 12: ('wagtail.blocks.DateBlock', (), {'required': False}), 13: ('wagtail.blocks.TimeBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 15: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'help_text': 'Event registration URL', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 11), ('date', 12), ('time', 13), ('location', 14), ('description', 15), ('image', 16), ('registration_link', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 21: ('wagtail.blocks.StructBlock', [[('image', 20), ('caption', 14)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {}), 23: ('wagtail.blocks.TextBlock', (), {'help_text': 'Testimonial text'}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('quote', 23), ('author', 24), ('role', 25), ('avatar', 16)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {}), 28: ('wagtail.blocks.CharBlock', (), {'max_length': 150}), 29: ('wagtail.blocks.TextBlock', (), {'required': False}), 30: ('wagtail.blocks.EmailBlock', (), {'required': False}), 31: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 32: ('wagtail.blocks.StructBlock', [[('name', 24), ('role', 28), ('bio', 29), ('photo', 16), ('email', 30), ('phone', 31)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {}), 34: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': False}), 35: ('wagtail.blocks.RichTextBlock', (), {}), 36: ('wagtail.blocks.StructBlock', [[('rule_number', 34), ('title', 11), ('description', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {}), 38: ('wagtail.blocks.RawHTMLBlock', (), {})})),
            ],
            options={
                'verbose_name': 'Flexible Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('gallery', 3), ('rich_text', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'verbose_name': 'Gallery Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RulesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('rules', 4), ('rich_text', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('rule_number', 0), ('title', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {})})),
            ],
            options={
                'verbose_name': 'Rules Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VolunteerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction to volunteering')),
                ('requirements', wagtail.fields.RichTextField(blank=True, help_text='Volunteer requirements')),
                ('registration_form_url', models.URLField(blank=True, help_text='External registration form URL')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('testimonials', 6)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Testimonial text'}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('quote', 1), ('author', 2), ('role', 3), ('avatar', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {})})),
            ],
            options={
                'verbose_name': 'Volunteer Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Welcome to ARC', max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.StreamField([('hero', 6), ('about', 10), ('events', 19), ('gallery', 22), ('testimonials', 27), ('team', 33), ('rules', 37), ('rich_text', 38), ('html', 39)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subheading text', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Hero description', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Call to action button text', 'max_length': 100, 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'Call to action button link', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('description', 2), ('background_image', 3), ('cta_text', 4), ('cta_link', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section title', 'max_length': 255}), 8: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'About content'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional image', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('content', 8), ('image', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 12: ('wagtail.blocks.DateBlock', (), {'required': False}), 13: ('wagtail.blocks.TimeBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 15: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'help_text': 'Event registration URL', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 11), ('date', 12), ('time', 13), ('location', 14), ('description', 15), ('image', 16), ('registration_link', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Events Section'}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 21: ('wagtail.blocks.StructBlock', [[('image', 20), ('caption', 14)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'label': 'Gallery Section'}), 23: ('wagtail.blocks.TextBlock', (), {'help_text': 'Testimonial text'}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('quote', 23), ('author', 24), ('role', 25), ('avatar', 16)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {'label': 'Testimonials'}), 28: ('wagtail.blocks.CharBlock', (), {'max_length': 150}), 29: ('wagtail.blocks.TextBlock', (), {'required': False}), 30: ('wagtail.blocks.EmailBlock', (), {'required': False}), 31: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 32: ('wagtail.blocks.StructBlock', [[('name', 24), ('role', 28), ('bio', 29), ('photo', 16), ('email', 30), ('phone', 31)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {'label': 'Team/Organizers'}), 34: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': False}), 35: ('wagtail.blocks.RichTextBlock', (), {}), 36: ('wagtail.blocks.StructBlock', [[('rule_number', 34), ('title', 11), ('description', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'label': 'Rules Section'}), 38: ('wagtail.blocks.RichTextBlock', (), {'label': 'Rich Text Content'}), 39: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Raw HTML'})})),
                ('hero_background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
